### ISSUE TITLE
Add functionality for planning double-sessions

### ISSUE THREAD

**Issue by LarsSelbekk** [mathiazom/rezervo-web#13]
Using the current view, it can be difficult to find combinations of activities which can be completed in sequence, e.g. PyramideSpin for 1h, 15m break and then Smidig.

One solution could be a Timeline-view, which could show activities side-by-side if their start- and end-times overlap. To make it most useful, it should be aware of which activities are at the same locations in some way, as it is usually impractical to travel to another gym between sessions.

Another solution could be to use some simple rules to find possible pairs, e.g. "same location && end1 + 5m <= start2 <= end1 + 30m", and then suggest them in a modal, or show an icon for "compatible double session" on those classes, with a link to go to, or perhaps highlighting in a lighter color which classes are compatible with the currently selected classes.

This issue is for @AdrianAndersen to procrastinate exam studying with.

**Comment by AdrianAndersen** [comment]
I think this is kind of redundant now that you can filter based on locations. It would also introduce a lot of extra complexity for a not-that-sought-after feature. 🚚
