### ISSUE TITLE
Today-button sometimes goes to the wrong week

### ISSUE THREAD

**Issue by LarsSelbekk** [mathiazom/rezervo-web#136]
This was tested on FSC on Edge Windows.
E.g. at 2024-05-07T14:00, I was scrolled to week 18 after logging in, and when clicking the Today-button. Also, week 20 seems to always be skipped when clicking through the weeks, and week 22 appears twice in a row, with the only difference apparently being whether the Les Mills classes were capitalized.

**Comment by AdrianAndersen** [comment]
Caching issue. I suspect this will be fixed once [we obliterate the week offset concept](https://github.com/mathiazom/rezervo-web/pull/134)

**Comment by AdrianAndersen** [comment]
I am pretty sure this was fixed by https://github.com/mathiazom/rezervo-web/pull/134. At least I have not experienced this again after that was deployed.  OK to close as resolved @LarsSelbekk?

**Comment by LarsSelbekk** [comment]
> I am pretty sure this was fixed by https://github.com/mathiazom/rezervo-web/pull/134. At least I have not experienced this again after that was deployed.  OK to close as resolved @LarsSelbekk?

Yep can confirm, no issue now.
